export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_TO_CART = 'ADD_TO_CART';
export const SELECT_CART_PRODUCT = 'SELECT_CART_PRODUCT';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';
export const SELECT_ALL_PRODUCTS = 'SELECT_ALL_PRODUCTS'
export const REMOVE_CART_TIME = 'REMOVE_CART_TIME'
export const CLEAR_CART = 'CLEAR_CART'
export const PRODUCT_FAVORITE = 'PRODUCT_FAVORITE'